apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permittering-og-omstilling
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  team: permittering-og-nedbemanning
  port: 3000
  ingresses:
    - https://permittering-og-omstilling.labs.nais.io/permittering-og-omstilling
  liveness:
    path: /permittering-og-omstilling/api/internal/isAlive
    initialDelay: 5
  readiness:
    path: /permittering-og-omstilling/api/internal/isReady
    initialDelay: 5
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"
