apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permittering-og-omstilling
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{ version }}
  team: permittering-og-nedbemanning
  port: 3000
  ingresses:
    - https://arbeidsgiver.nav.no/permittering-og-omstilling
  liveness:
    path: /permittering-og-omstilling/api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /permittering-og-omstilling/api/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 2
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.nav.no
        - host: utwe983u.api.sanity.io
  envFrom:
    - secret: permittering-og-omstilling-secrets
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
