name: Build and deploy

on: [push]

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/permittering-og-omstilling:${{ github.sha }}

jobs:
  compile-test-and-build:
    name: Build and run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-cache-
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build application
        run: |
          yarn run build
      - name: Build tag and push Docker container
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build . -t ${IMAGE}
          echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} --password-stdin
          echo ${IMAGE}
          docker push ${IMAGE}

  deploy-to-dev-gcp:
    name: Deploy to dev-gcp
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/skjemaer-og-regelverk'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY_TEAM }}
          CLUSTER: dev-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/dev-gcp.yaml
          PRINT_PAYLOAD: true

  deploy-to-labs-gcp:
    name: Deploy to labs-gcp
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/skjemaer-og-regelverk'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY_TEAM }}
          CLUSTER: labs-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/labs-gcp.yaml
          PRINT_PAYLOAD: true

  deploy-to-prod-gcp:
    name: Deploy to prod-gcp
    if: github.ref == 'refs/heads/main'
    needs: compile-test-and-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_KEY_TEAM }}
          CLUSTER: prod-gcp
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/prod-gcp.yaml
          PRINT_PAYLOAD: true
